image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      stack test
      docker-compose pull

  - command: |
      stack test
      docker-compose up

ports:
  - port: 5432
    onOpen: ignore
  - port: 8081
    onOpen: open-browser

vscode:
  extensions:
    - haskell.haskell
    - justusadam.language-haskell
