image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      stack test
      docker-compose pull

  - command: |
      stack test
      docker-compose up
      docker-compose run -T -e PGPASSWORD=pwd -v $PWD/schema.sql:/schema.sql postgres psql -h postgres -U user -d db -w -f /schema.sql

vscode:
  extensions:
    - haskell.haskell
    - justusadam.language-haskell
