version: '3'

services:
  postgres:
    image: postgres:14-alpine
    container_name: haskell-training-postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pwd
      - POSTGRES_DB=db
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - default

  pgadmin:
    image: dpage/pgadmin4:6.10
    container_name: haskell-training-pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.com
      - PGADMIN_DEFAULT_PASSWORD=password
    links:
      - postgres:postgres
    depends_on:
      - postgres
    volumes:
      - ./dump:/dump
    ports:
      - 8081:80
    networks:
      - default

networks:
  default:
    driver: bridge
