name:                haskell-training
version:             0.1.0.0
homepage:            https://github.com/tweag/haskell-training#readme
license:             OtherLicense
author:              Marco Perone
maintainer:          marco.perone@tweag.io
copyright:           2022 Tweag I/O
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - containers
  - text

library:
  source-dirs:      src

executables:
  game-engine:
    source-dirs:    game-engine
    main:           Main.hs
    dependencies:
      haskell-training
